EnterpriseAssignment/Controllers/ItemTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnterpriseAssignment.Models;
using GoogleDriveRestAPI_v3.Models;

namespace EnterpriseAssignment.Controllers
{
    [Authorize]
    public class ItemTypesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ItemTypes
        public ActionResult Index()
        {
            var itemTypes = db.ItemTypes.Include(i => i.Category);
            return View(itemTypes.ToList());
        }

        // GET: ItemTypes/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemTypes.Find(id);
            if (itemType == null)
            {
                return HttpNotFound();
            }
            return View(itemType);
        }

        // GET: ItemTypes/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        // POST: ItemTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Image,CategoryId")] ItemType itemType, HttpPostedFileBase file)
        {

            string ext = Path.GetExtension(file.FileName).ToLower();

            if (ext == ".png" || ext == ".jpg" || ext == ".jpeg")
            {
                if (ModelState.IsValid)
                {

                    itemType.Image = GoogleDriveFilesRepository.FileUpload(file);
                    db.ItemTypes.Add(itemType);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            else
            {
                ViewBag.FileFormatError = "Only PNG, JPG and JPEG formats are accepted";
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", itemType.CategoryId);
            return View(itemType);
        }

        // GET: ItemTypes/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemTypes.Find(id);
            if (itemType == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", itemType.CategoryId);
            return View(itemType);
        }

        // POST: ItemTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Image,CategoryId")] ItemType itemType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(itemType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", itemType.CategoryId);
            return View(itemType);
        }

        // GET: ItemTypes/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemType itemType = db.ItemTypes.Find(id);
            if (itemType == null)
            {
                return HttpNotFound();
            }
            return View(itemType);
        }

        // POST: ItemTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            ItemType itemType = db.ItemTypes.Find(id);
            db.ItemTypes.Remove(itemType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnterpriseAssignment/Views/Shared/_ItemCard.cshtml
@using Microsoft.AspNet.Identity;
@model EnterpriseAssignment.Models.Item


<div class="card col-md-3 mr-1">
    <img src="https://drive.google.com/uc?export=view&id=@Model.ItemType.Image" class="card-img-top" alt="...">
    <h5 class="card-title">@Html.DisplayFor(modelItem => Model.ItemType.Name)</h5>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">@Html.DisplayNameFor(model => model.Owner.Email): @Html.DisplayFor(modelItem => Model.Owner.Email)</li>
        <li class="list-group-item">@Html.DisplayNameFor(model => model.Quality): @Html.DisplayFor(modelItem => Model.Quality.Name)</li>
        <li class="list-group-item">@Html.DisplayNameFor(model => model.Quantity): @Html.DisplayFor(modelItem => Model.Quantity)</li>
        <li class="list-group-item">@Html.DisplayNameFor(model => model.Price): @Html.DisplayFor(modelItem => Model.Price)</li>
    </ul>

    @if (Model.OwnerId == User.Identity.GetUserId())
    {
        <div class="card-body">
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
        </div>
    }
</div>

EnterpriseAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNet.Identity
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link" })</li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">@Html.ActionLink("Categories", "Index", "Categories", null, new { @class = "nav-link" })</li>
                        }
                        <li class="nav-item">@Html.ActionLink("Item Types", "Index", "ItemTypes", null, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Items", "Index", "Items", null, new { @class = "nav-link" })</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>