EnterpriseAssignment/Models/Item.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EnterpriseAssignment.Models
{
    public class Item
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        [Required(ErrorMessage = "The quantity must be defined")]
        [Index("UN_OwnerId_Quality_Price", 4, IsUnique = true)]
        [Range(1, int.MaxValue, ErrorMessage = "Only positive numbers allowed")]
        public int Quantity { get; set; }

        [Required(ErrorMessage = "The price must be defined")]
        [Range(1, int.MaxValue, ErrorMessage = "Only positive numbers allowed")]
        [Index("UN_OwnerId_Quality_Price", 1, IsUnique = true)]
        public float Price { get; set; }

        [Index("UN_OwnerId_Quality_Price", 2, IsUnique = true)]
        public string OwnerId { get; set; }
        public virtual ApplicationUser Owner { get; set; }

        [Required(ErrorMessage = "The quality name must be defined")]
        [Index("UN_OwnerId_Quality_Price", 3, IsUnique = true)]
        [Display(Name = "Quality")]
        public long QualityId { get; set; }
        public Quality Quality { get; set; }

        [Required(ErrorMessage = "An Item Type must be selected")]
        [Display(Name = "Item Type")]
        public long ItemTypeId { get; set; }
        public ItemType ItemType { get; set; }
    }
}

EnterpriseAssignment/Models/ItemType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EnterpriseAssignment.Models
{
    public class ItemType
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        [Required(ErrorMessage = "The ItemType name must be defined")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "The length of the category name must be between 2 and 50")]
        public string Name { get; set; }

        public string Image { get; set; }

        [Required(ErrorMessage = "A category must be selected")]
        [Display(Name = "Category")]
        public long CategoryId { get; set; }
        public Category Category { get; set; }

        public virtual ICollection<Item> Items { get; set; }
    }
}

EnterpriseAssignment/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnterpriseAssignment.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;

namespace EnterpriseAssignment.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        public ActionResult Index(int? p)
        {
            ViewBag.OwnerId = new SelectList(db.Users, "Id", "UserName");

            if (Session["OwnerId"] != null)
            {

                string ownerId = Session["OwnerId"].ToString();

                var items = db.Items.Include(i => i.ItemType).Include(i => i.Owner).Include(i => i.Quality).Where(x => x.OwnerId == ownerId);
                List<Item> itemsList = new List<Item>();
                itemsList = items.ToList();
                itemsList.Reverse();
                return View(itemsList.ToPagedList(p ?? 1, 6));
            }

            else
            {
                var items = db.Items.Include(i => i.ItemType).Include(i => i.Owner).Include(i => i.Quality);
                List<Item> itemsList = new List<Item>();
                itemsList = items.ToList();
                itemsList.Reverse();
                Session["OwnerId"] = null;
                return View(itemsList.ToPagedList(p ?? 1, 6));
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string ownerId, int? p)
        {

            ViewBag.OwnerId = new SelectList(db.Users, "Id", "UserName");

            var sellerId = (from c in db.Items
                     where c.OwnerId == ownerId
                     select c.OwnerId).FirstOrDefault();

            if (sellerId != null)
            {
                
                var items = db.Items.Include(i => i.ItemType).Include(i => i.Owner).Include(i => i.Quality).Where(x => x.OwnerId == ownerId);
                List<Item> itemsList = new List<Item>();
                itemsList = items.ToList();
                itemsList.Reverse();
                Session["OwnerId"] = ownerId;
                return View(itemsList.ToPagedList(p ?? 1, 6));
            }

            else
            {
                var items = db.Items.Include(i => i.ItemType).Include(i => i.Owner).Include(i => i.Quality);
                List<Item> itemsList = new List<Item>();
                itemsList = items.ToList();
                itemsList.Reverse();
                Session["OwnerId"] = null;
                return View(itemsList.ToPagedList(p ?? 1, 6));
            }
        }

        // GET: Items/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create()
        {
            ViewBag.ItemTypeId = new SelectList(db.ItemTypes, "Id", "Name");
            //ViewBag.OwnerId = new SelectList(db.ApplicationUsers, "Id", "Email");
            ViewBag.QualityId = new SelectList(db.Qualities, "Id", "Name");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Quantity,Price,OwnerId,QualityId,ItemTypeId")] Item item)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    item.OwnerId = User.Identity.GetUserId();
                    db.Items.Add(item);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                catch (Exception e)
                {
                    ViewBag.Duplicate = "Duplicate entries - This item is already registered with the same quality, quantity and price";
                }
            }

            ViewBag.ItemTypeId = new SelectList(db.ItemTypes, "Id", "Name", item.ItemTypeId);
            //ViewBag.OwnerId = new SelectList(db.ApplicationUsers, "Id", "Email", item.OwnerId);
            ViewBag.QualityId = new SelectList(db.Qualities, "Id", "Name", item.QualityId);
            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(long? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);

            if (item == null)
            {
                return HttpNotFound();
            }

            if (item.OwnerId != User.Identity.GetUserId())
            {
                return RedirectToAction("Index");
            }

            ViewBag.ItemTypeId = new SelectList(db.ItemTypes, "Id", "Name", item.ItemTypeId);
            ViewBag.QualityId = new SelectList(db.Qualities, "Id", "Name", item.QualityId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Quantity,Price,OwnerId,QualityId,ItemTypeId")] Item item)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    db.Entry(item).State = EntityState.Modified;
                    item.OwnerId = User.Identity.GetUserId();
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                catch (Exception e)
                {
                    ViewBag.Duplicate = "Duplicate entries - This item is already registered with the same quality, quantity and price";
                }
            }
            ViewBag.ItemTypeId = new SelectList(db.ItemTypes, "Id", "Name", item.ItemTypeId);
            //ViewBag.OwnerId = new SelectList(db.ApplicationUsers, "Id", "Email", item.OwnerId);
            ViewBag.QualityId = new SelectList(db.Qualities, "Id", "Name", item.QualityId);
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            if (item.OwnerId != User.Identity.GetUserId())
            {
                return RedirectToAction("Index");
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {

            Item item = db.Items.Find(id);

            if (item.OwnerId != User.Identity.GetUserId())
            {
                return RedirectToAction("Index");
            }

            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EnterpriseAssignment/Views/Items/Create.cshtml
@model EnterpriseAssignment.Models.Item

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@if (ViewBag.Duplicate != null)
{
    <div class="alert alert-danger">
        @ViewBag.Duplicate;
    </div>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QualityId, "Quality", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("QualityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QualityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemTypeId, "Item Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ItemTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ItemTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-secondary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnterpriseAssignment/Views/Items/Delete.cshtml
@model EnterpriseAssignment.Models.Item

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quality.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quality.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-secondary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EnterpriseAssignment/Views/Items/Details.cshtml
@model EnterpriseAssignment.Models.Item

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemType.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemType.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quality.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quality.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EnterpriseAssignment/Views/Items/Edit.cshtml
@model EnterpriseAssignment.Models.Item

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@if (ViewBag.Duplicate != null)
{
    <div class="alert alert-danger">
        @ViewBag.Duplicate;
    </div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QualityId, "QualityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("QualityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.QualityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemTypeId, "ItemTypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ItemTypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ItemTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-secondary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnterpriseAssignment/Views/Items/Index.cshtml
@using Microsoft.AspNet.Identity;
@model IPagedList<EnterpriseAssignment.Models.Item>
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        <div class="col-md-3 form-group">
            <div class="col-md-10">
                @Html.DropDownList("OwnerId", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Filter" class="btn btn-secondary" />
            </div>
        </div>
    </div>
}
<div class="col-md-12 row">
    @foreach (var item in Model)
    {
        @Html.Partial("_ItemCard", item)
    }
</div>

@Html.PagedListPager(Model, p => Url.Action("Index", "Items", new { p }))   